/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.sample1.classicmodels.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.sample1.classicmodels.models.query.*;

@Service
public class ClassicmodelsQueryExecutorServiceImpl implements ClassicmodelsQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ClassicmodelsQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("classicmodelsWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<MyqueryResponse> executeMyquery(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("myquery", params, MyqueryResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Downloadable exportMyquery(ExportType exportType, Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.exportNamedQueryData("myquery", params, exportType, MyqueryResponse.class, pageable);
    }

}


