/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.sample1.classicmodels.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class MyqueryResponse implements Serializable {

    @ColumnAlias("addressLine2")
    private String addressLine2;
    @ColumnAlias("sum(phone)")
    private BigDecimal sum_phone_;

    public String getAddressLine2() {
        return this.addressLine2;
    }

    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    public BigDecimal getSum_phone_() {
        return this.sum_phone_;
    }

    public void setSum_phone_(BigDecimal sum_phone_) {
        this.sum_phone_ = sum_phone_;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof MyqueryResponse)) return false;
        final MyqueryResponse myqueryResponse = (MyqueryResponse) o;
        return Objects.equals(getAddressLine2(), myqueryResponse.getAddressLine2()) &&
                Objects.equals(getSum_phone_(), myqueryResponse.getSum_phone_());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAddressLine2(),
                getSum_phone_());
    }
}
